name: Docker Java Build

on:
  #  push:
  #    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: docker-test-java:latest
        build-args: |
          SECRET_KEY=${{ vars.SECRET_KEY }}
          DB_USER=${{ vars.DB_USER }}
          DB_PASSWORD=${{ vars.DB_PASSWORD }}
          USER_NAME=${{ vars.USER_NAME }}
          USER_PASSWORD=${{ vars.USER_PASSWORD }}
          VAPID_PUBLIC_KEY=${{ vars.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY=${{ vars.VAPID_PRIVATE_KEY }}
