name: Docker Java Build

on:
  #  push:
  #    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ vars.SECRET_KEY }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      USER_NAME: ${{ vars.USER_NAME }}
      USER_PASSWORD: ${{ vars.USER_PASSWORD }}
      VAPID_PUBLIC_KEY: ${{ vars.VAPID_PUBLIC_KEY }}
      VAPID_PRIVATE_KEY: ${{ vars.VAPID_PRIVATE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Build Docker image
      run: |
        docker build \
          --build-arg SECRET_KEY="$SECRET_KEY" \
          --build-arg DB_USER="$DB_USER" \
          --build-arg DB_PASSWORD="$DB_PASSWORD" \
          --build-arg USER_NAME="$USER_NAME" \
          --build-arg USER_PASSWORD="$USER_PASSWORD" \
          --build-arg VAPID_PUBLIC_KEY="$VAPID_PUBLIC_KEY" \
          --build-arg VAPID_PRIVATE_KEY="$VAPID_PRIVATE_KEY" \
          -t docker-test-java .
